# Generated by Django 5.0.6 on 2024-07-24 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0005_remove_snippet_shared_with'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedSnippets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_snippets', to='snippet.snippet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
