# Generated by Django 5.0.6 on 2024-07-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0006_likedsnippets'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='num_like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
