# Generated by Django 5.0.6 on 2024-07-24 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0007_snippet_num_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likedsnippets',
            old_name='shared_with',
            new_name='snippets_liked',
        ),
    ]
