# Generated by Django 5.0.6 on 2024-07-24 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0008_rename_shared_with_likedsnippets_snippets_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedsnippets',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
