# Generated by Django 5.0.6 on 2024-07-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0009_alter_likedsnippets_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='snippet',
            name='generation_failed',
            field=models.BooleanField(default=False),
        ),
    ]
