# Generated by Django 5.0.6 on 2024-07-25 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0004_snippet_attempts_snippet_generation_failed'),
        ('snippet', '0009_alter_likedsnippets_user'),
    ]

    operations = [
    ]
