# Generated by Django 5.0.6 on 2024-07-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0010_snippet_attempts_snippet_generation_failed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='generation_failed',
        ),
    ]
