apiVersion: apps/v1
kind: Deployment
metadata:
  name: snippet-django
  labels:
    app: snippet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snippet
  template:
    metadata:
      labels:
        app: snippet
    spec:
      initContainers:
        - name: collectstatic
          image: ghcr.io/charlyrousseau/snippet-django:latest
          command: ["python", "manage.py", "collectstatic", "--noinput"]
          volumeMounts:
            - name: static-files
              mountPath: /app/staticfiles
      containers:
        - name: snippet-django
          image: ghcr.io/charlyrousseau/snippet-django:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: static-files
              mountPath: /app/staticfiles
          env:
            - name: DJANGO_PRODUCTION
              value: "True"
            - name: DJANGO_SETTINGS_MODULE
              value: "snippet_project.settings"
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: snippet-secrets
                  key: DJANGO_SECRET_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: snippet-secrets
                  key: database_url
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: snippet-secrets
                  key: OPENAI_API_KEY
            - name: MINIO_ENDPOINT_URL
              value: "https://minio-api.playground-charly.fr"
            - name: MINIO_BUCKET_NAME
              value: "test"
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: access_key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: secret_key
      volumes:
        - name: static-files
          persistentVolumeClaim:
            claimName: snippet-static-pvc
      imagePullSecrets:
        - name: ghcr-secret
