apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/data/snippet-media
  storageClassName: local-path
