apiVersion: v1
kind: ConfigMap
metadata:
  name: snippet-nginx-config
data:
  nginx.conf: |
    user  nginx;

    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;

    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {

        default_type  application/octet-stream;

        access_log  /var/log/nginx/access.log;

        server {
            listen 80;

            location / {
                proxy_pass http://snippet-django-service/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location /static/ {
                proxy_pass http://snippet-django-service/static/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;


                types {
                    text/html  html htm shtml;
                    text/css   css;
                    text/xml   xml;
                    image/gif  gif;
                    image/jpeg jpg jpeg;
                    application/javascript js;
                    application/atom+xml   atom;
                    application/rss+xml    rss;
                    font/ttf   ttf;
                    font/otf   otf;
                    font/woff  woff;
                    font/woff2 woff2;
                }

            }
        }
    }