apiVersion: apps/v1
kind: Deployment
metadata:
  name: snippet-nginx
  labels:
    app: snippet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snippet
  template:
    metadata:
      labels:
        app: snippet
    spec:
      containers:
        - name: snippet-nginx
          image: ghcr.io/charlyrousseau/snippet-nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config-volume
          configMap:
            name: snippet-nginx-config
      imagePullSecrets:
        - name: ghcr-secret
