name: Build and Test

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/charlyrousseau/snippet-django:${{ github.sha }} .
          docker tag ghcr.io/charlyrousseau/snippet-django:${{ github.sha }} ghcr.io/charlyrousseau/snippet-django:latest

      - name: Run Tests
        run: |
          docker run --rm ghcr.io/charlyrousseau/snippet-django:${{ github.sha }} python manage.py test
      
      - name: Update .env File
        if: github.ref == 'refs/heads/main'
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
    
      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/charlyrousseau/snippet-django:${{ github.sha }}
          docker push ghcr.io/charlyrousseau/snippet-django:latest
