name: Build and Test

on:
  push:
    branches:
      - "**" # Matches all branches except `main`

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/charlyrousseau/snippet-django:${{ github.sha }} .
          docker tag ghcr.io/charlyrousseau/snippet-django:${{ github.sha }} ghcr.io/charlyrousseau/snippet-django:latest

      - name: Run Tests
        run: |
          docker run --rm ghcr.io/charlyrousseau/snippet-django:${{ github.sha }} python manage.py test

      - name: Push Docker image
        run: |
          docker push ghcr.io/charlyrousseau/snippet-django:${{ github.sha }}
          docker push ghcr.io/charlyrousseau/snippet-django:latest

      - name: Update Kubernetes manifests
        run: |
          sed -i 's|image: ghcr.io/charlyrousseau/snippet-django:.*|image: ghcr.io/charlyrousseau/snippet-django:${{ github.sha }}|g' k8s/django-deployment.yaml
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add k8s/django-deployment.yaml
          git commit -m "Update image tag to ${GITHUB_SHA}"
          git push
